import type { Metadata } from "next";
import { montserrat } from "./utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${montserrat.className} antialiased`}>
        <main className=" mt-16 flex justify-center w-full items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
